CREATE TABLE APP_USER (
    ID NUMBER GENERATED ALWAYS AS IDENTITY
        START WITH 1
        INCREMENT BY 1
        CACHE 20
        NOCYCLE
        NOT NULL,
    USERNAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    PASSWORD VARCHAR2(255) NOT NULL,
    ROLE VARCHAR2(50) NOT NULL,
    ENABLED NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_APP_USER PRIMARY KEY (ID),
    CONSTRAINT UK_APP_USER_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UK_APP_USER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CHK_APP_USER_ENABLED CHECK (ENABLED IN (0,1))
);