CREATE TABLE REFRESH_TOKEN (
    ID NUMBER GENERATED ALWAYS AS IDENTITY 
        START WITH 1
        INCREMENT BY 1
        CACHE 20
        NOCYCLE
        NOT NULL,
    TOKEN VARCHAR2(500) NOT NULL,
    USER_ID NUMBER NOT NULL,
    EXPIRY_DATE TIMESTAMP NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP,
    CONSTRAINT PK_REFRESH_TOKEN PRIMARY KEY (ID),
    CONSTRAINT UK_REFRESH_TOKEN UNIQUE (TOKEN),
    CONSTRAINT FK_REFRESH_USER
        FOREIGN KEY (USER_ID)
        REFERENCES APP_USER(ID)
        ON DELETE CASCADE,
    CONSTRAINT UK_REFRESH_USER UNIQUE (USER_ID)
);